version: "3.8"
services:
  solr1: &solr
    build: ./solr
    ports:
      - 8983:8983
      - 9854:9854
      - 5005:5005
    command:
      - /bin/bash
      - -c
      - "solr start -c -z zoo:2181 && /opt/solr/prometheus-exporter/bin/solr-exporter -p 9854 -z zoo:2181"
    depends_on:
      - zoo
    volumes:
      - ./solr/mnt/configsets/wikipedia:/opt/solr/server/solr/configsets/wikipedia
      - ./solr/mnt/solr1/data:/var/solr/data
      - ./solr/mnt/solr1/logs:/var/solr/logs
      - ./solr/mnt/solr1/benchmarks:/var/solr/benchmarks
    environment:
      SOLR_HOST: solr1
      SOLR_OPTS: "-XX:+FlightRecorder -XX:FlightRecorderOptions=stackdepth=256 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      SOLR_MODULES: "ltr"

  solr2:
    <<: *solr
    ports:
      - 8984:8983
      - 9855:9854
      - 5006:5005
    volumes:
      - ./solr/mnt/configsets/wikipedia:/opt/solr/server/solr/configsets/wikipedia
      - ./solr/mnt/solr2/data:/var/solr/data
      - ./solr/mnt/solr2/logs:/var/solr/logs
      - ./solr/mnt/solr2/benchmarks:/var/solr/benchmarks
    environment:
      SOLR_HOST: solr2
      SOLR_OPTS: "-XX:+FlightRecorder -XX:FlightRecorderOptions=stackdepth=256 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      SOLR_MODULES: "ltr"

  zoo:
    image: zookeeper:3.7
    ports:
      - 2181:2181
    volumes:
      - ./zookeeper/mnt/data:/data
      - ./zookeeper/mnt/datalog:/datalog
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/mnt/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/mnt/data:/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --storage.tsdb.retention.time=2d

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    env_file:
      - grafana/grafana.env
    volumes:
      - ./grafana/mnt/data:/var/lib/grafana
      - ./grafana/mnt/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/mnt/datasources:/etc/grafana/provisioning/datasources

  jmeter:
    build: ./jmeter
    volumes:
      - ./jmeter/benchmarks:/var/jmeter/benchmarks
